name: azure-cli
summary: Microsoft Azure CLI 2.0
description: |
 A great cloud needs great tools; we're excited to introduce Azure CLI 2.0, our
 next generation multi-platform command line experience for Azure.
version: "2.0.26"
confinement: classic
grade: stable
apps:
  az:
    # https://bugs.launchpad.net/snappy/+bug/1664427
    command: usr/bin/python -m azure.cli
    environment:
      # TODO Why not use the normal directory?
      AZURE_CONFIG_DIR: $SNAP_USER_COMMON
parts:
  azure-cli:
    plugin: python
    source: https://azurecliprod.blob.core.windows.net/releases/azure-cli-2.0.25.tar.gz
    source-subdir: src/azure-cli
    organize:
      # PEP 394 says you should use `python3`, but the client uses `python`.
      usr/bin/python3.5: "usr/bin/python"
    build-packages:
      - build-essential
      - python3-dev
      - python3-wheel
      - libffi-dev
      - libssl-dev
    prepare: |
       set -e # Don't continue on error.
       packages_dir="$(readlink -e ../packages)"
       /usr/bin/pip3 wheel -w $packages_dir src/azure-cli-core src/azure-cli-nspkg src/azure-cli-command_modules-nspkg src/command_modules/azure-cli-*
