name: azure-cli
summary: Microsoft Azure CLI 2.0
description: |
 A great cloud needs great tools; we're excited to introduce Azure CLI 2.0, our
 next generation multi-platform command line experience for Azure.
version: "2.0.26"
confinement: classic
grade: stable
apps:
  az:
    # https://bugs.launchpad.net/snappy/+bug/1664427
    command: usr/bin/python -m azure.cli
    completer: az.completion
    environment:
      # TODO Why not use the normal directory?
      # config directory is pointed to the directory common to all revisions of your snap for the given user, $HOME/snap/azure-cli/common
      # We probably want this to be the global ~/.azure directory so remove this?
      AZURE_CONFIG_DIR: $SNAP_USER_COMMON
parts:
  completion:
    plugin: dump
    # source: https://azurecliprod.blob.core.windows.net/releases/azure-cli-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    # source-checksum: sha256/3d49bf2cac972f441d4b78e1ea38ba43f18a3568fb5799eb3aa920551ccd6965
    # source: https://gist.githubusercontent.com/derekbekoe/6dbb82badf4c79d9fd0774b11c8d39b3/raw/95d59a9445a56d4e9622f6221d5b4bbdae40b8c2/az.completion
    # source-checksum: sha256/8b6a0ba929418c8b1d2f4383ba22cca8ee814123938274f6a047cc0278f72b6e
    source: https://derekb.blob.core.windows.net/public/az-comp.tar.gz
    source-checksum: sha256/af772f417f5e609306eeffa3a077d2fdac04e8acc960a3d1484bcde6aad1ac3f
    stage:
      - az.completion
  azure-cli:
    plugin: python
    source: https://azurecliprod.blob.core.windows.net/releases/azure-cli-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    source-checksum: sha256/3d49bf2cac972f441d4b78e1ea38ba43f18a3568fb5799eb3aa920551ccd6965
    source-subdir: src/azure-cli
    python-version: python3
    organize:
      # PEP 394 says you should use `python3`, but the client uses `python`.
      usr/bin/python3.5: "usr/bin/python"
    build-packages:
      - build-essential
      - python3-dev
      - python3-wheel
      - libffi-dev
      - libssl-dev
    prepare: |
       set -e
       packages_dir="$(readlink -e ../packages)"
       /usr/bin/pip3 wheel -w $packages_dir src/azure-cli-core src/azure-cli-nspkg src/azure-cli-command_modules-nspkg src/command_modules/azure-cli-*
