name: azure-cli
summary: Microsoft Azure CLI 2.0
description: |
 A great cloud needs great tools; we're excited to introduce Azure CLI 2.0, our
 next generation multi-platform command line experience for Azure.
version: "2.0.26"
confinement: classic
grade: stable
apps:
  az:
    # https://bugs.launchpad.net/snappy/+bug/1664427
    command: usr/bin/python -m azure.cli
    completer: az.snap.completion
    aliases: [az]
parts:
  completion:
    plugin: dump
    source-type: git
    source: https://github.com/derekbekoe/azure-cli.git
    source-branch: snap-package
    # source-tag: azure-cli-$SNAPCRAFT_PROJECT_VERSION
    stage:
      - az.snap.completion
  azure-cli:
    plugin: azure
    source-type: git
    source: https://github.com/derekbekoe/azure-cli.git
    source-branch: snap-package
    # source-tag: azure-cli-$SNAPCRAFT_PROJECT_VERSION
    source-subdir: src/azure-cli
    python-version: python3
    organize:
      # PEP 394 says you should use `python3`, but the client uses `python`.
      usr/bin/python3.5: "usr/bin/python"
    build-packages:
      - build-essential
      - python3-dev
      - python3-wheel
      - libffi-dev
      - libssl-dev
    stage-packages:
      - libssl1.0.0
